### ISSUE TITLE
Incorrect Rendering

### ISSUE THREAD

**Issue by hengzhe-zhang** [Doma1204/ChatPoe#1]
The ChatPoe extension is not rendering correctly, which affects the experience and readability of the chat messages. Could you update this extension? Thanks!

**Comment by Doma1204** [comment]
Thank you for reporting the issue. It appears that the Poe frontend underwent a major update, causing the styling to be completely off. Please wait for further updates.

**Comment by Doma1204** [comment]
@hengzhe-zhang The extension has been updated
